messages:
  starting-message: "Starting CoordVerter."
  stopping-message: "Stopping CoordVerter."
  command-user-error: "<dark_grey>This command can only be used by players.</dark_grey>"
  missing-permission-error: "<dark_grey>You lack the rights to use this command. Womp womp</dark_grey>"
  argument-amount-error: "<dark_grey>Usage: /convert <world> <x> <y> <z></dark_grey>"
  invalid-format-error: "<dark_grey>Invalid coordinate format.</dark_grey>"
  unknown-dimension-error: "<dark_grey>Unknown dimension. Options are:\n<aqua>Overworld</aqua>, <red>Nether</red></dark_grey>"
  overworld-name: "Overworld"
  nether-name: "Nether"
  prefix-output: "<newline>"
  overworld-output: "<newline><font:uniform><dark_grey><click:copy_to_clipboard:${x_ow} ${y_ow} ${z_ow}><hover:show_text:'Copy to Clipboard'><aqua>${overworld}</aqua></hover></click>|${x_ow}|${y_ow}|${z_ow}|</dark_grey></font>"
  nether-output: "<newline><font:uniform><dark_grey><click:copy_to_clipboard:${x_nt} ${y_nt} ${z_nt}><hover:show_text:'Copy to Clipboard'><red>${nether}</red></hover></click>|${x_nt}|${y_nt}|${z_nt}|</dark_grey></font>"
  suffix-output: "<newline>"